modules:
  server: ziaserver
  router: ziarouter
  static: ziastatic
  prompt: ziaprompt

server:
  http: 8080
  https: 4200

router:
  /:
    handler: static

static:
  base_directory: ./static
  default:
    - index.html
    - index.php

prompt:
