modules:
  http:
    route:
      /:
        cgi: php
        auth: true
        name: truc
      /blog/*:
        auth: true
        name: m
      /blog/new:
        name: perlinpinpin$=
      /blog/admin/*:
        auth: false
        name: lacampagne-adm

      /blog:
        name: foo
        auth: true
        routes:
          /new:
            name: perlinpinpin
        default: foo
  cgi:
    - php
    - foo
    - bar

  php:
    host: localhost
    port: 1234


###########

http:
  cgi: php
  auth: true
  handler: cgi
  routes:
    /blog:
      auth: true
      handler: m # /blog
      routes:
        /new:
          handler: perlinpinpin$=
        /admin/foo:
          auth: false
          handler: lacampagne-adm
        /*:
          handler: zef


cgi:
  php:
    host: localhost
    port: 1234
  ruby:
  perl:
